name: Check Star Count

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  check-stars:
    runs-on: ubuntu-latest
    steps:

      - name: Get Star Count
        id: get_stars
        run: |
          stars=$(curl -sH "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/stargazers" | jq '. | length')
          echo "::set-output name=stars::$stars"
      
      - name: Compare Star Count
        id: compare_stars
        run: |
          if [ "${{ steps.get_stars.outputs.stars }}" -ge 5 ]; then
            echo "Stars >= 5"
            echo "::set-output name=trigger::true"
          else
            echo "Stars < 5"
            echo "::set-output name=trigger::false"
          fi
      
      - name: Create Issue
        if: ${{ steps.compare_stars.outputs.trigger == 'true' }}
        run: |
          issue_title="Re-enable Generating Duck Addresses"
          issue_body="The repository now has 5 or more stars. This means that a reapplication can be submitted for cors.sh"
          curl -X POST -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" \
          -d "{\"title\":\"$issue_title\",\"body\":\"$issue_body\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues"
